name: Test

on:
  push:
    branches: ['master']
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3']
        os: ['ubuntu-latest']
        failure: [false]
        include:
          - { php: '8.4', os: 'ubuntu-latest', failure: true } # Psalm does not support PHP 8.4 yet
          - { php: '8.5', os: 'ubuntu-latest', failure: true } # '8.5' means 'nightly'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Install PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          tools: 'composer:v2'
          coverage: 'xdebug'
      - name: 'PHP'
        run: 'php -v'

      - name: 'Composer'
        run: 'composer install'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'PHPUnit'
        run: 'php vendor/bin/phpunit --coverage-text'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'Psalm'
        run: |
          composer remove --dev -W 'phpunit/phpunit'
          composer require --dev -W 'vimeo/psalm=^5.0' 'nikic/php-parser=^4.0'
          php vendor/bin/psalm --shepherd --php-version=${{ matrix.php }}
        continue-on-error: '${{ matrix.failure }}'
      - name: 'Infection'
        run: |
          composer remove --dev -W 'vimeo/psalm'
          composer require --dev -W phpunit/phpunit infection/infection
          php vendor/bin/infection
        continue-on-error: '${{ matrix.failure }}'
