name: TestOld

on:
  push:
    branches: ['master']
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3']
        os: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Install PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          tools: 'composer:v1'
          coverage: 'xdebug'
      - name: 'PHP'
        run: 'php -v'

      - name: 'Composer'
        run: 'composer install'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'PHPUnit'
        run: 'php vendor/bin/phpunit --coverage-text'
